name: CI - Build & Test Docker Image

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repository
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Set up Docker Buildx (for better, faster Docker builds)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 3. Build Docker image
      - name: Build Docker image
        run: |
          docker build -t calculator-app .

      # 4. Run container to ensure it works
      - name: Run container for testing
        run: |
          docker run -d --name calc-test -p 8080:80 calculator-app
          sleep 5
          echo "Testing container..."
          curl -I http://localhost:8080

      # 5. Stop container
      - name: Stop container
        run: docker stop calc-test

      # 6. Remove container
      - name: Remove container
        run: docker rm calc-test

    
      # OPTIONAL â€” PUSH IMAGE
      # - name: Push image to DockerHub
      #   run: |
      #     docker tag calculator-app ${{ secrets.DOCKERHUB_USERNAME }}/calculator-app:latest
      #     docker push ${{ secrets.DOCKERHUB_USERNAME }}/calculator-app:latest
